<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputPath>..\..\Bin\</OutputPath>
        <RootNamespace>ET</RootNamespace>
        <AssemblyName>Loader</AssemblyName>        
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Share\Analyzer\Share.Analyzer.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="..\Model\Model.csproj" />
        <ProjectReference Include="..\ThirdParty\ThirdParty.csproj" />        
    </ItemGroup>    

</Project>
