<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="..\UnityDemo\Assets\Scripts\Core\**\*.cs">
            <Link>MiniEtLib\%(RecursiveDir)%(FileName)%(Extension)</Link>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\UnityDemo\Assets\Scripts\Codes\Model\Generate\ClientServer\**\*.cs">
            <Link>AppGenerate\%(RecursiveDir)%(FileName)%(Extension)</Link>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ThirdParty\ThirdParty.csproj"/>
    </ItemGroup>

</Project>
